### PR TITLE
Add option to delete already processed files

### LINKED ISSUE #21: Delete .rollbar files after they've been processed
I can only speak for the PHP library of Rollbar, but most `.rollbar` log files contain just one exception to report (due in part to the fact that the [file's name is based on calling `microtime()`](https://github.com/rollbar/rollbar-php/blob/master/src/rollbar.php#L948)). As a result, Rollbar ends up creating one file/exception, and none of these files are ever cleaned up, leading to a ton of extra unused files sitting around. 

I talked briefly with @brianr about this, but it would be nice to have the option to have the `rollbar-agent` delete any `.rollbar` file that has already been processed by the agent. It may be as simple as just calling `os.remove()` in [`process()`](https://github.com/rollbar/rollbar-agent/blob/master/rollbar-agent#L226-229).

### PR DESCRIPTION
**Pull request by nrjones8**
Closes #21

### CODE REVIEW

**Comment by brianr** [comment]
Thanks @nrjones8 !

I think this looks good. @coryvirok can you review as well?

**Comment by coryvirok** [comment]
Looks good. The only weird thing is that we need to wait until the next call of `scan_app()` to delete the file state. That's fine though.

**Comment by brianr** [comment]
Thanks @nrjones8 ! This is up on pypi as version 0.3.11.

**Comment by nrjones8** [comment]
Awesome, thank you @brianr and @coryvirok !

**Comment by nrjones8** [comment]
It looks like accessing `self.config['delete_processed_files']`([here](https://github.com/rollbar/rollbar-agent/blob/master/rollbar-agent#L532)) isn't actually the correct key to be accessing; it should be something like `self.config[appname]['delete_processed_files']`, since `self.config` isn't actually just a dictionary of configuration parameters -- this ends up throwing a `KeyError` from `self.config`. Sorry I missed this!

**Pull request merged**
